### PR TITLE
SQCPPGHA-5 Support Running on Linux ARM64 with generic CLI Scanner

### PR DESCRIPTION
**Pull request by enzo-pellegrini**

### CODE REVIEW

**Comment by michael-jabbour-sonarsource** [comment]
Now that the ARM64 scanner CLI is available, we can make the following changes in this PR:

 - Update the scanner version to 6.1
 - Use the aarch64 version on ARM64
 - No need to install a compatible JRE in the action anymore

**Review by michael-jabbour-sonarsource — APPROVED** [review]
LGTM.

I did some validation in the following runs:
 - Windows: [here](https://github.com/sonarsource-cfamily-examples/windows-msbuild-gh-actions-sq/actions/runs/9872429157/job/27262525525)
   - scanner cache hit: [here](https://github.com/sonarsource-cfamily-examples/windows-msbuild-gh-actions-sq/actions/runs/9872547558/job/27262874126)
 - MacOS X86: [here](https://github.com/sonarsource-cfamily-examples/macos-cmake-compdb-gh-actions-sq/actions/runs/9872455611/job/27262604693)
   - scanner cache hit: [here](https://github.com/sonarsource-cfamily-examples/macos-cmake-compdb-gh-actions-sq/actions/runs/9872530011/job/27262820336)
 - MacOS ARM64: [here](https://github.com/sonarsource-cfamily-examples/macos-cmake-compdb-gh-actions-sq/actions/runs/9873182184/job/27264887103)
 - Linux X86: [here](https://github.com/sonarsource-cfamily-examples/linux-autotools-gh-actions-sq/actions/runs/9872470277/job/27262646589)
   - scanner cache hit: [here](https://github.com/sonarsource-cfamily-examples/linux-autotools-gh-actions-sq/actions/runs/9873197828/job/27264936057)

@enzo-pellegrini Could you ask for a second review from AE for this as well?

**Comment by michael-jabbour-sonarsource** [comment]
I think it would also make sense to release a new version of the action once this is merged, so that we can consume the new version in our onboarding examples...

**Comment by michael-jabbour-sonarsource** [comment]
As a side note (not related to this PR), more of a question to the AE squad.

I noticed that the tests workflow [isn't triggered on the master branch](https://github.com/SonarSource/sonarqube-github-c-cpp/actions/workflows/tests.yml?query=branch%3Amaster) in this repo, because [the workflow is enabled only on main](https://github.com/SonarSource/sonarqube-github-c-cpp/blob/fb9e804d4786d2828697b21af0f3dfc5d8d481e1/.github/workflows/tests.yml#L5) (and [there is no branch named main here](https://github.com/SonarSource/sonarqube-github-c-cpp/branches) as far as I can see). Is this intentional?

**Review by michael-jabbour-sonarsource — APPROVED** [review]

**Comment by 7PH** [comment]
> I noticed that the tests workflow isn't triggered on the master branch in this repo, because the workflow is enabled only on main (and there is no branch named main here as far as I can see). Is this intentional?

From a quick look, that should definitively run on the `master` branch (not `main`), I've created [a ticket](https://sonarsource.atlassian.net/browse/SQCPPGHA-7) to track this, but otherwise feel free to fix this as part of the scope of this pull request.

**Review by 7PH — APPROVED** [review]
LGTM ✅ No FV since @michael-jabbour-sonarsource reviewed it with FV

**Pull request merged**
